create table public.captions (
  id uuid not null default gen_random_uuid (),
  created_datetime_utc timestamp with time zone not null default now(),
  modified_datetime_utc timestamp with time zone null,
  content character varying null,
  is_public boolean not null,
  profile_id uuid not null,
  image_id uuid not null,
  humor_flavor_id bigint null,
  is_featured boolean not null default false,
  caption_request_id bigint null,
  like_count bigint not null default '0'::bigint,
  llm_prompt_chain_id bigint null,
  constraint captions_pkey primary key (id),
  constraint captions_caption_request_id_fkey foreign KEY (caption_request_id) references caption_requests (id) on update CASCADE on delete CASCADE,
  constraint captions_humor_flavor_id_fkey foreign KEY (humor_flavor_id) references humor_flavors (id) on delete set null,
  constraint captions_image_id_fkey foreign KEY (image_id) references images (id) on delete CASCADE,
  constraint captions_llm_prompt_chain_id_fkey foreign KEY (llm_prompt_chain_id) references llm_prompt_chains (id) on delete CASCADE,
  constraint captions_profile_id_fkey foreign KEY (profile_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_captions_image_id on public.captions using btree (image_id) TABLESPACE pg_default;

create index IF not exists idx_captions_like_count_desc_id on public.captions using btree (like_count desc, id) TABLESPACE pg_default;

create index IF not exists captions_image_id_idx on public.captions using btree (image_id) TABLESPACE pg_default;



create table public.images (
  id uuid not null default gen_random_uuid (),
  created_datetime_utc timestamp with time zone not null default now(),
  modified_datetime_utc timestamp with time zone null,
  url character varying null,
  is_common_use boolean null default false,
  profile_id uuid null default auth.uid (),
  additional_context character varying null,
  is_public boolean null default false,
  image_description text null,
  celebrity_recognition text null,
  embedding public.vector null,
  constraint images_pkey primary key (id),
  constraint images_profile_id_fkey foreign KEY (profile_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_images_is_common_use on public.images using btree (is_common_use) TABLESPACE pg_default
where
  (is_common_use = true);

create index IF not exists idx_images_is_public on public.images using btree (is_public) TABLESPACE pg_default
where
  (is_public = true);

create index IF not exists idx_images_profile_id on public.images using btree (profile_id) TABLESPACE pg_default;





create table public.profiles (
  id uuid not null,
  created_datetime_utc timestamp with time zone null default now(),
  modified_datetime_utc timestamp with time zone null,
  first_name character varying null,
  last_name character varying null,
  email text null,
  is_superadmin boolean not null default false,
  is_in_study boolean not null default false,
  is_matrix_admin boolean not null default false,
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;






create table public.humor_flavor_mix (
  id bigint generated by default as identity not null,
  created_datetime_utc timestamp with time zone not null default now(),
  humor_flavor_id bigint not null,
  caption_count smallint not null,
  constraint humor_flavor_mix_pkey primary key (id),
  constraint humor_flavor_mix_humor_flavor_id_fkey foreign KEY (humor_flavor_id) references humor_flavors (id) on delete CASCADE
) TABLESPACE pg_default;





create table public.caption_requests (
  id bigint generated by default as identity not null,
  created_datetime_utc timestamp with time zone not null default now(),
  profile_id uuid not null,
  image_id uuid not null,
  constraint caption_requests_pkey primary key (id),
  constraint caption_requests_image_id_fkey foreign KEY (image_id) references images (id) on delete CASCADE,
  constraint caption_requests_profile_id_fkey foreign KEY (profile_id) references profiles (id) on update CASCADE
) TABLESPACE pg_default;